"""followers

Revision ID: 66256092079d
Revises: 00c3db52dbe7
Create Date: 2019-10-04 02:24:56.736505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66256092079d'
down_revision = '00c3db52dbe7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
